#include<iostream>

using namespace std;

int main()
{
    /////////////// C++ Exception Handling /////////////////
    /*
        throw
            - throws an exception
            - followed by an argument

        try { code that may throw an exception }
            - you place code that may throw an exception in a try block
            - if the code throws an exception the try block is exited
            - the thrown exception is handled by a catch handler
            - if no catch handler exists the program terminates

        catch(Exception ex) { code to handle the exception }
            - code that handles the exception
            - can have multiple catch handlers
            - may or may not cause the program to terminate
    */
}